server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: false
      routes:
        - id: ms-inventory-tools
          uri: lb://MS-INVENTORY
          predicates:
            - Path=/tools/**
        - id: ms-inventory-categories
          uri: lb://MS-INVENTORY
          predicates:
            - Path=/categories/**
        - id: ms-rental
          uri: lb://MS-RENTAL
          predicates:
            - Path=/rentals/**
        - id: ms-clients
          uri: lb://MS-CLIENTS
          predicates:
            - Path=/customers/**
        - id: ms-users
          uri: lb://MS-USERS
          predicates:
            - Path=/users/**
        - id: ms-kardex
          uri: lb://MS-KARDEX
          predicates:
            - Path=/kardex/**
        - id: ms-amounts
          uri: lb://MS-AMOUNTS
          predicates:
            - Path=/penalties/**
        - id: ms-reports
          uri: lb://MS-REPORTS
          predicates:
            - Path=/reports/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/