server:
  port: ${PORT:0}

spring:
  application:
    name: ms-users
  datasource:
    url: jdbc:mysql://mysql:3306/toolrent_users?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 19Luna!Cody03
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://toolrent-keycloak:8080/realms/toolrent
          jwk-set-uri: http://toolrent-keycloak:8080/realms/toolrent/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
